### ISSUE TITLE
does not work on linux

### ISSUE THREAD

**Issue by mucbuc** [mucbuc/plusi#1]

**Comment by mucbuc** [comment]
let run = require( 'runjs' ).run
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
